### ISSUE TITLE
Error when trying to "Enter the Plurality Book community repo"

### ISSUE THREAD

**Issue by tflaj** [gov4git/desktop-application#109]
Hello Team! 

I am getting the following error (screenshot) when trying to "Enter the Plurality Book community repo"

![Image](https://github.com/gov4git/desktop-application/assets/98186439/1bf0a8f0-348e-4fdd-8380-23a24dce0c39)

@dworthen

**Comment by dworthen** [comment]
@tflaj, I believe I was able to identify and resolve this issue. 

Please launch the application and wait for it to upgrade to the latest version, 0.15.1. The app should prompt you to update when ready. 

![image](https://github.com/gov4git/desktop-application/assets/624870/9fd70fd3-ceb2-4905-80ad-b6a9ee44b8ff)

After the update, log out and then log back in. You will then need to go through the join process for the plurality community again. Please let me know if this works for you or not.
