### ISSUE TITLE
error on start

### ISSUE THREAD

**Issue by petar** [gov4git/desktop-application#114]
I get this bug on a fresh app start.

[logs.txt](https://github.com/gov4git/desktop-application/files/14451625/logs.txt)
<img width="1079" alt="Screenshot 2024-02-29 at 9 45 28 AM" src="https://github.com/gov4git/desktop-application/assets/285131/7874114d-1d3c-488b-9c4a-3e286268b523">

**Comment by dworthen** [comment]
@petar, Checking the logs it looks like it is failing to load data for gov4git/sample-project-gov.public? It looks like the community repos for sample-project have been deleted, perhaps through testing. I will add some logic to clear out data for previous communities that no longer exist.

**Comment by petar** [comment]
Yep! Good catch. This one is high-value to fix, because the app refuses to work after this condition. Thank you!

**Comment by dworthen** [comment]
This is a scenario I catch and report which is working on my local version of the app

![image](https://github.com/gov4git/desktop-application/assets/624870/363f09b6-7353-4862-818d-f0464a41d235)

But strangely when I run the production app I get the same error you have. I have no idea why my error capture and recovery logic is behaving differently between the local running version and the hosted production version. I will dive into this now to get it resolved.
