### ISSUE TITLE
Error: stdout maxBuffer length exceeded

### ISSUE THREAD

**Issue by nishio** [gov4git/desktop-application#116]
I have installed old version of gov4git, requested to join pluralitybook, accepted, however I have no vote credit.
Today I got vote credit and received an e-mail to notify it. Following the mail, I installed 0.15.1 on Mac.
When I run the new app, the previous membership exists. However it won't work.
I don't know I have to refresh something or delete some cache file?

GUI says
```
Error
Message: Failed to load motions. Error: stdout maxBuffer length exceeded

Next Steps
Please close and relaunch the application. If the error persists, please save the logs, [open a new issue](https://github.com/gov4git/desktop-application/issues/new), and upload the saved log file to the issue.
```

The error persists. So I made this issue. Here is the log:

[logs.txt](https://github.com/gov4git/desktop-application/files/14457430/logs.txt)

**Comment by dworthen** [comment]
@nishio, Thanks for the report. The latest version of the app, v0.15.3, resolves this issue. Next time you start the desktop application it should prompt you to update to v0.15.3 after a few minutes. Let me know if updating the app does not resolve the issue for you.
