### ISSUE TITLE
Error when opening gov4git

### ISSUE THREAD

**Issue by jason-entenmann** [gov4git/desktop-application#119]
**[logs-03012024.txt](https://github.com/gov4git/desktop-application/files/14464235/logs-03012024.txt)**: Message: Failed to load communities. Error: Command failed: C:\Users\jentenmann\AppData\Local\Programs\gov4git-desktop-app\resources\app.asar.unpacked\node_modules\@gov4git\js-client\bin\gov4git.exe group list --name everybody --config C:\Users\jentenmann\.gov4git\86d94d00fa6eac94c1309e18bfc84c5f07d0cd5a97b283802c912af576887aed.json -v 2024-03-01T09:44:02-08:00 INF /home/runner/work/gov4git/gov4git/gov4git/cmd/root.go:69 gov4git version: dev-rev-43f0fe9-2024-02-21, os: windows, arch: amd64 goroutine 1 [running]: runtime/debug.Stack() /opt/hostedtoolcache/go/1.21.7/x64/src/runtime/debug/stack.go:24 +0x5e github.com/gov4git/lib4git/must.mkErr(...) /home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.32/must/must.go:37 github.com/gov4git/lib4git/must.Panic(...) /home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.32/must/must.go:43 github.com/gov4git/lib4git/must.Errorf({0xab4bf0?, 0xc0001b4ed0}, {0x9a4f2c?, 0xc0001376a8?}, {0xc000137678?, 0xc000137708?, 0xc0001376d0?}) /home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.32/must/must.go:47 +0x65 github.com/gov4git/lib4git/must.Assertf(...) /home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.32/must/must.go:61 github.com/gov4git/lib4git/git.PullOnce({0xab4bf0, 0xc0001b4ed0}, 0xc0000a6b10, {0xc0000ac080, 0x38}, {0xc000090520, 0x1, 0x1}) /home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.32/git/sync.go:137 +0x405 github.com/gov4git/lib4git/git.(*clonedNoCache).Pull(0xc0000a6b40?, {0xab4bf0?, 0xc0001b4ed0?}) /home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.32/git/nocache.go:56 +0x15d github.com/gov4git/lib4git/git.NoCache.clone({{0x0?, 0x878ba0?}}, {0xab4bf0, 0xc0001b4ed0}, {{0xc0000ac080?, 0xc0001b4e70?}, {0xc0000866a0?, 0x10652a0?}}, 0x0) /home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.32/git/nocache.go:40 +0x205 github.com/gov4git/lib4git/git.NoCache.CloneOne(...) /home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.32/git/nocache.go:23 github.com/gov4git/lib4git/git.CloneOne({0xab4bf0, 0xc0001b4ed0}, {{0xc0000ac080?, 0x0?}, {0xc0000866a0?, 0x0?}}) /home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.32/git/clone.go:32 +0xb9 github.com/gov4git/gov4git/v2/proto/id.Clone(...) /home/runner/work/gov4git/gov4git/proto/id/id.go:54 github.com/gov4git/gov4git/v2/proto/gov.Clone(...) /home/runner/work/gov4git/gov4git/proto/gov/gov.go:19 github.com/gov4git/gov4git/v2/proto/member.ListGroupUsers({0xab4bf0, 0xc0001b4ed0}, {{0xc0000ac080?, 0x0?}, {0xc0000866a0?, 0x0?}}, {0xc00011a0c0, 0x9}) /home/runner/work/gov4git/gov4git/proto/member/member.go:102 +0x65 github.com/gov4git/gov4git/v2/gov4git/cmd.glob..func38.1() /home/runner/work/gov4git/gov4git/gov4git/cmd/group.go:61 +0x50 github.com/gov4git/lib4git/must.Try1Thru[...](0x0?) /home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.32/must/must.go:116 +0x6e github.com/gov4git/gov4git/v2/gov4git/api.Invoke1[...](0x0?) /home/runner/work/gov4git/gov4git/gov4git/api/result.go:33 +0x3d github.com/gov4git/gov4git/v2/gov4git/cmd.glob..func38(0xc000199d00?, {0x99570d?, 0x4?, 0x99560d?}) /home/runner/work/gov4git/gov4git/gov4git/cmd/group.go:58 +0x25 github.com/spf13/cobra.(*Command).execute(0x1007e20, {0xc0000b8050, 0x5, 0x5}) /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x863 github.com/spf13/cobra.(*Command).ExecuteC(0x1002500) /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3a5 github.com/spf13/cobra.(*Command).Execute(...) /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968 github.com/gov4git/gov4git/v2/gov4git/cmd.Execute() /home/runner/work/gov4git/gov4git/gov4git/cmd/root.go:107 +0x1a main.main.func1() /home/runner/work/gov4git/gov4git/gov4git/main.go:15 +0xf github.com/gov4git/lib4git/must.TryWithStack(0x0?) /home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.32/must/must.go:97 +0x79 main.main() /home/runner/work/gov4git/gov4git/gov4git/main.go:14 +0x1e

**Comment by dworthen** [comment]
#121 resolved this issue.
