### ISSUE TITLE
fyi, v0.15.5 still stumbles on missing gov repo

### ISSUE THREAD

**Issue by petar** [gov4git/desktop-application#128]
- when i start the app, i get a message "https://github.com/gov4git/sample-project is not a Gov4Git managed repo"
- but there is no UI (empty canvas) below it
- i stumbled by mistake into the observation that if i click my username in the top right corner, the UI appears; and the list of repositories is empty
- the empty list, in my case, highlights another issue: i had three repositories in the list earlier (before deleting the sample-project gov repo). the other two repos are still healthy.

**Comment by dworthen** [comment]
Version 0.15.6 resolves this issue. Communities that have been deleted are now removed from the desktop app and does not impact the functionality in the rest of the app (the list is no longer empty)
