### ISSUE TITLE
Error when voting for an issue -- plurality book MVP

### ISSUE THREAD

**Issue by jason-entenmann** [gov4git/desktop-application#32]
I attempted to vote for an issue, I received a successful vote notification within the voting module, but an error popped up at the top of the window with the following error. Logs attached.

[error log g4g issue 103123.txt](https://github.com/gov4git/desktop-application/files/13220623/error.log.g4g.issue.103123.txt)

Message: Failed to cast vote. Error: Command failed: C:\Users\jentenmann\AppData\Local\Programs\gov4git-desktop-app\resources\app.asar.unpacked\node_modules\@gov4git\js-client\bin\gov4git.exe ballot vote --name github/issues/20 --choices prioritize --strengths 25 --config C:\Users\jentenmann\.gov4git\8ea6982c37c79c338efe64eebe9bbfdcddc6dd58911d58be65ba046853ca23e5.json file does not exist

**Comment by dworthen** [comment]
Resolved with #38
