### ISSUE TITLE
how to log into the desktop app with a different user?

### ISSUE THREAD

**Issue by petar** [gov4git/desktop-application#39]
I wanted to use the app as a different user. So I tried entering the other user's details in the config screen (after having been logged as petar already). And when I hit "Save" I get an error.Is there a way to clear the app's persistent memory? Or what procedure would you recommend for logging in with different users? This is coming up as a useful operation while troubleshooting the system.

<img width="1068" alt="Screenshot 2023-11-01 at 11 24 52 AM" src="https://github.com/gov4git/desktop-application/assets/285131/14c2db89-9ba1-4fef-bdeb-07c7d2ceba37">

[gov4git-app-log.txt](https://github.com/gov4git/desktop-application/files/13230568/gov4git-app-log.txt)

**Comment by banklesschick** [comment]
Seems I am having same issue still: https://github.com/gov4git/desktop-application/issues/40

**Comment by dworthen** [comment]
I am able to replicate this issue when the second user PAT token does not have sufficient privileges. For the PAT token, the top level `repo` option must be selected, not just the individual scopes under repo. #41 checks that the PAT token has sufficient privileges prior to logging in and presents a new message if it does not.

![image](https://github.com/gov4git/desktop-application/assets/624870/52c374c0-b5cb-4d09-92ad-9f42e2020c09)

@banklesschick , please open the app and let it update to latest version, 0.6.4, and let me know if you are still unable to switch user accounts.

**Comment by dworthen** [comment]
This was resolved with the release of gov4git/desktop-application#64 since it now uses a device auth flow instead of requiring users to create and provide a PAT. The app is able to request the privileges it requires.

**Comment by dworthen** [comment]
The app allows users to log out to then select a different account to log in with.
