### ISSUE TITLE
pull-request screen is showing issues as well

### ISSUE THREAD

**Issue by petar** [gov4git/desktop-application#78]
Desktop App Version 0.11.2
Community github.com/gov4git/roadmap

The app is showing the same set of issues in both screens.
I cannot see the one open (and managed PR https://github.com/gov4git/roadmap/pull/25) in the UI.

I am guessing you are filtering out only issues somewhere in the code (for both screens).

**Comment by dworthen** [comment]
@petar, published a fix to the filtering issue. Feel free to reopen if not resolved.
