### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by KasiaSun** [gov4git/desktop-application#84]
```
Error checking satus of gov4git-identity-public. 


: { "name": "HttpError", "status": 500, "request": { "method": "GET", "url": "https://api.github.com/repos/kasiasun/gov4git-identity-public", "headers": { "accept": "application/vnd.github.v3+json", "user-agent": "octokit-request.js/8.1.6 Node.js/18.17.1 (darwin; x64)", "authorization": "Bearer [REDACTED]" } } }

Error checking satus of gov4git-identity-private. 500: { "name": "HttpError", "status": 500, "request": { "method": "GET", "url": "https://api.github.com/repos/kasiasun/gov4git-identity-private", "headers": { "accept": "application/vnd.github.v3+json", "user-agent": "octokit-request.js/8.1.6 Node.js/18.17.1 (darwin; x64)", "authorization": "Bearer [REDACTED]" } } }

```

![Image](https://github.com/gov4git/desktop-application/assets/47511016/e76fd064-7d5f-4a71-9646-6c1b7980c961)

**Comment by KasiaSun** [comment]
cc @dworthen @petar

**Comment by dworthen** [comment]
@KasiaSun, That issue appears to come from GitHub's API SDK. It looks like the GitHub API may have been down or experiencing degraded performance. The app has backoff retry logic so for that error to surface the app failed to reach the API endpoint after 3 attempts. The latest release, gov4git/desktop-application#86 wraps the API logic and presents the following message when the endpoint is not reachable. 

![image](https://github.com/gov4git/desktop-application/assets/624870/e3726c4d-6c8e-41ef-a604-229df9eadb13)

Let me know what you think or if you would like to update the wording.
